//
// Generated file, do not edit! Created by nedtool 5.1 from Messages/CtrltoOCSTopoAdd.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CTRLTOOCSTOPOADD_M_H
#define __CTRLTOOCSTOPOADD_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0501
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Messages/CtrltoOCSTopoAdd.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet CtrltoOCSTopoAdd
 * {
 *     int inGate = -1;
 *     int outGate = -1;
 * }
 * </pre>
 */
class CtrltoOCSTopoAdd : public ::omnetpp::cPacket
{
  protected:
    int inGate;
    int outGate;

  private:
    void copy(const CtrltoOCSTopoAdd& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CtrltoOCSTopoAdd&);

  public:
    CtrltoOCSTopoAdd(const char *name=nullptr, short kind=0);
    CtrltoOCSTopoAdd(const CtrltoOCSTopoAdd& other);
    virtual ~CtrltoOCSTopoAdd();
    CtrltoOCSTopoAdd& operator=(const CtrltoOCSTopoAdd& other);
    virtual CtrltoOCSTopoAdd *dup() const override {return new CtrltoOCSTopoAdd(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getInGate() const;
    virtual void setInGate(int inGate);
    virtual int getOutGate() const;
    virtual void setOutGate(int outGate);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CtrltoOCSTopoAdd& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CtrltoOCSTopoAdd& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CTRLTOOCSTOPOADD_M_H

